# site
title: habits moodboard
baseurl: "/moodboard-100"
url: "https://zul.rocks"
favicon: "/assets/ico.png"
g_analytics: UA-12345678-1

# bio
header: Habit moodboard
desc: >
   A visual companion to my habit trackers

# posts
date_format: "%Y"

# build settings
markdown: kramdown
#theme: fry
remote_theme: lilykonings/fry
exclude:
  - Gemfile
  - Gemfile.lock






