# site
title: moodboard
baseurl: "/moodboard-100/"
url: "https://zulfadz.github.io"
favicon: "/assets/ico.png"
g_analytics: UA-12345678-1

# bio
header: 100-day habit moodboard
desc: >
   A companion to 100-day habit log trackers

# posts
date_format: "%Y"

# build settings
markdown: kramdown
#theme: fry
remote_theme: lilykonings/fry
exclude:
  - Gemfile
  - Gemfile.lock






